services:
  delivery:
    build: delivery/.
    ports:
      - "80:80"
    volumes:
      - "objects:/usr/share/nginx/objects"
  controlplane:
    build: controlplane/.
    ports:
      - "8080:8080"
    command: npm run dev
volumes:
  objects: